#write a program to input eight numbers from the user and display all the unique numbers once

s=set()
n1=int(input("Enter first number: "))
s.add(n1)
n2=int(input("Enter second number: "))
s.add(n2)
n3=int(input("Enter third number: "))
s.add(n3)
n4=int(input("Enter fourth number: "))
s.add(n4)
n5=int(input("Enter fifth number: "))
s.add(n5)
n6=int(input("Enter sixth number: "))
s.add(n6)
n7=int(input("Enter seventh number: "))
s.add(n7)
n8=int(input("Enter eighth number:"))
s.add(n8)

print(s)
